#!/bin/sh

### Script for cleaning the folder of the offshore wind park simulation
### HLRS, 2024-2025

rm log.* slurm.* 

# Lösche Ordner
rm -rf constant/polyMesh processor*

find . -maxdepth 1 -type d -regextype posix-extended -regex '\./[0-9]{1,9}' -exec rm -rf {} +

