#!/bin/sh

### Script for post-processing the offshore wind park simulation
### HLRS, 2024-2025

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm log.foamToVTK log.reconstructPar

find . -maxdepth 1 -type d -regextype posix-extended -regex '\./[0-9]{1,5}' -exec rm -rf {} +

runApplication reconstructPar
runApplication foamToVTK
