#!/bin/sh

### Script for post-processing the offshore wind park simulation
### HLRS, 2024-2025

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf VTK 
rm log.foamToVTK log.reconstructPar

runApplication reconstructPar
runApplication foamToVTK
